CREATE SCHEMA IF NOT EXISTS INOVATECH;
USE INOVATECH;

CREATE TABLE IF NOT EXISTS CLIENTES(
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME_CLIENTE VARCHAR(100) NOT NULL,
    CPF_CLIENTE VARCHAR(20) NOT NULL,
    TELEFONE_CLIENTE VARCHAR(13) NOT NULL,
    DATANASC_CLIENTE DATE NOT NULL,
    STATUSFIDELIDADE_CLIENTE VARCHAR(100) NOT NULL,
    CEP_CLIENTE VARCHAR(10) NOT NULL,
    RUA_CLIENTE VARCHAR(50) NOT NULL,
    NUMCASA_CLIENTE VARCHAR(5) NOT NULL,
    BAIRRO_CLIENTE VARCHAR(40) NOT NULL,
    UF_CLIENTE CHAR(2) NOT NULL
);

-- Inserir dados na tabela CLIENTES
INSERT INTO CLIENTES (NOME_CLIENTE, CPF_CLIENTE, TELEFONE_CLIENTE, DATANASC_CLIENTE, STATUSFIDELIDADE_CLIENTE, CEP_CLIENTE, RUA_CLIENTE, NUMCASA_CLIENTE, BAIRRO_CLIENTE, UF_CLIENTE)
VALUES ('Maria Oliveira', '12345678901', '11987654321', '1990-06-15', 'Ouro', '12345-678', 'Rua A', '101', 'Centro', 'SP'),
       ('João Santos', '98765432100', '11912345678', '1985-03-25', 'Prata', '23456-789', 'Rua B', '202', 'Jardim', 'RJ'),
       ('Ana Costa', '11122334455', '11943210987', '1992-11-10', 'Bronze', '34567-890', 'Rua C', '303', 'Vila Nova', 'MG');

-- Atualizar dados na tabela CLIENTES
UPDATE CLIENTES SET STATUSFIDELIDADE_CLIENTE = 'Diamante' WHERE ID_CLIENTE = 1;
UPDATE CLIENTES SET TELEFONE_CLIENTE = '11987654322' WHERE ID_CLIENTE = 2;

-- Deletar dados na tabela CLIENTES
DELETE FROM CLIENTES WHERE ID_CLIENTE = 3;

CREATE TABLE IF NOT EXISTS PRODUTOS(
    ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    CATEGORIA_PRODUTO VARCHAR(45) NOT NULL,
    QUANTIDADEESTOQUE_PRODUTO INT NOT NULL,
    PRECO_PRODUTO DECIMAL(10, 2) NOT NULL
);
-- Inserir dados na tabela PRODUTOS
INSERT INTO PRODUTOS (CATEGORIA_PRODUTO, QUANTIDADEESTOQUE_PRODUTO, PRECO_PRODUTO)
VALUES ('Tênis', 50, 150.00),
       ('Camiseta', 100, 49.90),
       ('Bolsa', 30, 79.99);

-- Atualizar dados na tabela PRODUTOS
UPDATE PRODUTOS SET QUANTIDADEESTOQUE_PRODUTO = 45 WHERE ID_PRODUTO = 1;
UPDATE PRODUTOS SET PRECO_PRODUTO = 45.90 WHERE ID_PRODUTO = 2;

-- Deletar dados na tabela PRODUTOS
DELETE FROM PRODUTOS WHERE ID_PRODUTO = 3;

CREATE TABLE IF NOT EXISTS FORNECEDORES(
    ID_FORNECEDOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME_FORNECEDOR VARCHAR(100) NOT NULL,
    TELEFONE_FORNECEDOR VARCHAR(13) NOT NULL,
    CPF_FORNECEDOR VARCHAR(20) NOT NULL,
    EMAIL_FORNECEDOR VARCHAR(50) NOT NULL
);

-- Inserir dados na tabela FORNECEDORES
INSERT INTO FORNECEDORES (NOME_FORNECEDOR, TELEFONE_FORNECEDOR, CPF_FORNECEDOR, EMAIL_FORNECEDOR)
VALUES ('Fornecedor A', '11987654321', '12345678901', 'fornecedorA@email.com'),
       ('Fornecedor B', '11912345678', '98765432100', 'fornecedorB@email.com'),
       ('Fornecedor C', '11943210987', '11122334455', 'fornecedorC@email.com');

-- Atualizar dados na tabela FORNECEDORES
UPDATE FORNECEDORES SET EMAIL_FORNECEDOR = 'novoEmailA@email.com' WHERE ID_FORNECEDOR = 1;
UPDATE FORNECEDORES SET TELEFONE_FORNECEDOR = '11987654322' WHERE ID_FORNECEDOR = 2;

-- Deletar dados na tabela FORNECEDORES
DELETE FROM FORNECEDORES WHERE ID_FORNECEDOR = 3;

CREATE TABLE IF NOT EXISTS VENDAS(
    ID_VENDA INT PRIMARY KEY AUTO_INCREMENT,
    VALOR_VENDA DECIMAL(10, 2) NOT NULL,
    ID_CLIENTE INT,
    CONSTRAINT FK_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE) ON DELETE CASCADE
);

-- Inserir dados na tabela VENDAS
INSERT INTO VENDAS (VALOR_VENDA, ID_CLIENTE)
VALUES (300.00, 1),
       (150.00, 2),
       (500.00, 1);

-- Atualizar dados na tabela VENDAS
UPDATE VENDAS SET VALOR_VENDA = 350.00 WHERE ID_VENDA = 1;
UPDATE VENDAS SET VALOR_VENDA = 180.00 WHERE ID_VENDA = 2;

-- Deletar dados na tabela VENDAS
DELETE FROM VENDAS WHERE ID_VENDA = 3;

CREATE TABLE IF NOT EXISTS PAGAMENTOS(
    FORMA_PAGAMENTO VARCHAR(30) NOT NULL,
    DATA_PAGAMENTO DATE NOT NULL,
    VALOR_PAGAMENTO DECIMAL(10, 2) NOT NULL,
    STATUS_PAGAMENTO VARCHAR(30) NOT NULL,
    ID_VENDA INT,
    PRIMARY KEY(ID_VENDA, DATA_PAGAMENTO),
    CONSTRAINT FK_ID_VENDA FOREIGN KEY (ID_VENDA) REFERENCES VENDAS(ID_VENDA) ON DELETE CASCADE
);

-- Inserir dados na tabela PAGAMENTOS
INSERT INTO PAGAMENTOS (FORMA_PAGAMENTO, DATA_PAGAMENTO, VALOR_PAGAMENTO, STATUS_PAGAMENTO, ID_VENDA)
VALUES ('Cartão de Crédito', '2024-01-15', 300.00, 'Pago', 1),
       ('Dinheiro', '2024-02-10', 150.00, 'Pago', 2),
       ('Cartão de Débito', '2024-03-05', 500.00, 'Pendente', 2);

-- Atualizar dados na tabela PAGAMENTOS
UPDATE PAGAMENTOS SET STATUS_PAGAMENTO = 'Pendente' WHERE ID_VENDA = 1;
UPDATE PAGAMENTOS SET VALOR_PAGAMENTO = 200.00 WHERE ID_VENDA = 2;

-- Deletar dados na tabela PAGAMENTOS
DELETE FROM PAGAMENTOS WHERE ID_VENDA = 3;

CREATE TABLE IF NOT EXISTS PRODUTOS_VENDAS(
    ID_PRODUTO INT,
    ID_VENDA INT,
    QNTDPRODUTO_VENDA INT NOT NULL,
    PRIMARY KEY(ID_PRODUTO, ID_VENDA),
    CONSTRAINT FK_ID_PRODUTO FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO),
    CONSTRAINT FK_ID_VENDA2 FOREIGN KEY(ID_VENDA) REFERENCES VENDAS(ID_VENDA)
);

-- Inserir dados na tabela PRODUTOS_VENDAS
INSERT INTO PRODUTOS_VENDAS (ID_PRODUTO, ID_VENDA, QNTDPRODUTO_VENDA)
VALUES (1, 1, 2),
       (2, 2, 3),
       (1, 2, 1);

-- Atualizar dados na tabela PRODUTOS_VENDAS
UPDATE PRODUTOS_VENDAS SET QNTDPRODUTO_VENDA = 3 WHERE ID_PRODUTO = 1 AND ID_VENDA = 1;
UPDATE PRODUTOS_VENDAS SET QNTDPRODUTO_VENDA = 4 WHERE ID_PRODUTO = 2 AND ID_VENDA = 2;

-- Deletar dados na tabela PRODUTOS_VENDAS
DELETE FROM PRODUTOS_VENDAS WHERE ID_PRODUTO = 1 AND ID_VENDA = 2;

CREATE TABLE IF NOT EXISTS PRODUTOS_FORNECEDORES(
    ID_PRODUTO INT,
    ID_FORNECEDOR INT,
    PRIMARY KEY(ID_PRODUTO, ID_FORNECEDOR),
    CONSTRAINT FK_ID_PRODUTO2 FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO),
    CONSTRAINT FK_ID_FORNECEDOR FOREIGN KEY(ID_FORNECEDOR) REFERENCES FORNECEDORES(ID_FORNECEDOR)
);

-- Inserir dados na tabela PRODUTOS_FORNECEDORES
INSERT INTO PRODUTOS_FORNECEDORES (ID_PRODUTO, ID_FORNECEDOR)
VALUES (1, 1),
       (2, 2),
       (2, 1);

-- Atualizar dados na tabela PRODUTOS_FORNECEDORES
UPDATE PRODUTOS_FORNECEDORES SET ID_FORNECEDOR = 2 WHERE ID_PRODUTO = 1 AND ID_FORNECEDOR = 1;
UPDATE PRODUTOS_FORNECEDORES SET ID_FORNECEDOR = 2 WHERE ID_PRODUTO = 2 AND ID_FORNECEDOR = 2;

-- Deletar dados na tabela PRODUTOS_FORNECEDORES
DELETE FROM PRODUTOS_FORNECEDORES WHERE ID_PRODUTO = 1 AND ID_FORNECEDOR = 3;


DROP DATABASE INOVATECH;
