CREATE DATABASE CADEIA_DE_SUPRIMENTOS;
USE CADEIA_DE_SUPRIMENTOS;

CREATE TABLE FORNECEDORES (
    ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
    NOME_EMPRESA VARCHAR(255) NOT NULL,
    ENDERECO_EMPRESA VARCHAR(255),
    PAIS_ORIGEM VARCHAR(100),
    PESSOA_CONTATO VARCHAR(100),
    TELEFONE VARCHAR(50)
);

-- COMANDOS DDL FORNECEDOR
-- CRIAR INDEX
CREATE INDEX IDX_NOME_EMPRESA 
ON FORNECEDORES (NOME_EMPRESA);

-- CRIAR VIEW
CREATE VIEW VISTA_FORNECEDORES AS
SELECT NOME_EMPRESA, ENDERECO_EMPRESA
FROM FORNECEDORES;

-- COMANDO ALTER ADD
ALTER TABLE FORNECEDORES ADD EMAIL VARCHAR(100);

-- COMANDO ALTER MODIFY COLUMN 
ALTER TABLE FORNECEDORES MODIFY COLUMN EMAIL VARCHAR(150);

-- COMANDO ALTER CHANGE COLUMN
ALTER TABLE FORNECEDORES CHANGE COLUMN EMAIL EMAIL_COMPLETO VARCHAR(150);

-- COMANDO ALTER ADD INDEX
ALTER TABLE FORNECEDORES ADD INDEX IDX_EMAIL (EMAIL_COMPLETO);

-- REMOVER ÍNDICE:
DROP INDEX IDX_EMAIL ON FORNECEDORES;

-- REMOVER VISÃO:
DROP VIEW VISTA_FORNECEDORES;

-- REMOVER DADOS
TRUNCATE TABLE FORNECEDORES;

-- ALTERAR NOME DA TABELA
RENAME TABLE FORNECEDORES TO FORNECEDOR;
RENAME TABLE FORNECEDOR TO FORNECEDORES;

-- COMENTARIOS NAS TABELAS
ALTER TABLE FORNECEDORES COMMENT = 'TABELA DE INFORMAÇÕES DOS FORNECEDORES';

-- ADICIONAR COMENTÁRIO A COLUMNA:
ALTER TABLE FORNECEDORES MODIFY EMAIL_COMPLETO VARCHAR(150) COMMENT 'EMAIL DO CONTATO QUE REPRESENTA O FORNECEDOR';

-- COMANDO ALTER DROP COLUMUN
ALTER TABLE FORNECEDORES DROP COLUMN EMAIL_COMPLETO;

-- CRIAR TABELA PRODUTO
CREATE TABLE PRODUTO (
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PRODUTO VARCHAR(255) NOT NULL,
    DESCRICAO TEXT,
    ESPECIFICACOES_TECNICAS TEXT,
    UNIDADE_MEDIDA VARCHAR(50),
    PRECO_UNITARIO DECIMAL(10, 2),
    QUANTIDADE_ESTOQUE INT DEFAULT 0,
    LOCALIZACAO_ARMZENAGEM VARCHAR(100),
    PONTO_RESSUPRIMENTO INT
);

-- COMANDOS DDL PRODUTO
-- CRIAR INDEX
CREATE INDEX IDX_NOME_PRODUTO 
ON PRODUTO (NOME_PRODUTO);

-- CRIAR VIEW
CREATE VIEW VISTA_PRODUTOS AS
SELECT NOME_PRODUTO, PRECO_UNITARIO
FROM PRODUTO;

-- COMANDO ALTER ADD
ALTER TABLE PRODUTO ADD CODIGO_BARRAS VARCHAR(100);

-- COMANDO ALTER MODIFY COLUMN 
ALTER TABLE PRODUTO MODIFY COLUMN CODIGO_BARRAS VARCHAR(150);

-- COMANDO ALTER CHANGE COLUMN
ALTER TABLE PRODUTO CHANGE COLUMN CODIGO_BARRAS CODIGO_BARRAS_COMPLETO VARCHAR(150);

-- COMANDO ALTER ADD INDEX
ALTER TABLE PRODUTO ADD INDEX IDX_CODIGO_BARRAS (CODIGO_BARRAS_COMPLETO);

-- REMOVER ÍNDICE:
DROP INDEX IDX_CODIGO_BARRAS ON PRODUTO;

-- REMOVER VISÃO:
DROP VIEW VISTA_PRODUTOS;

-- REMOVER DADOS
TRUNCATE TABLE PRODUTO;

-- ALTERAR NOME DA TABELA
RENAME TABLE PRODUTO TO PRODUTOS;
RENAME TABLE PRODUTOS TO PRODUTO;

-- COMENTÁRIOS NA TABELA
ALTER TABLE PRODUTO COMMENT = 'TABELA DE INFORMAÇÕES DOS PRODUTOS';

-- ADICIONAR COMENTÁRIO A COLUMNA:
ALTER TABLE PRODUTO MODIFY CODIGO_BARRAS_COMPLETO VARCHAR(150) COMMENT 'CÓDIGO DE BARRAS DO PRODUTO';

-- COMANDO ALTER DROP COLUMN
ALTER TABLE PRODUTO DROP COLUMN CODIGO_BARRAS_COMPLETO;

-- CRIAR TABELA PEDIDOCOMPRA
CREATE TABLE PEDIDOCOMPRA (
    ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    DATA_PEDIDO DATE NOT NULL,
    DATA_ENTREGA_ESPERADA DATE,
    STATUS_PEDIDOS ENUM('EM PROCESSAMENTO', 'ENVIADO', 'RECEBIDO', 'CANCELADO') NOT NULL,
    ID_FORNECEDOR INT,
    FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDORES(ID_FORNECEDOR)
);

-- COMANDOS DDL PEDIDOCOMPRA
-- CRIAR INDEX
CREATE INDEX IDX_DATA_PEDIDO 
ON PEDIDOCOMPRA (DATA_PEDIDO);

-- CRIAR VIEW
CREATE VIEW VISTA_PEDIDOS AS
SELECT DATA_PEDIDO, STATUS_PEDIDOS
FROM PEDIDOCOMPRA;

-- COMANDO ALTER ADD
ALTER TABLE PEDIDOCOMPRA ADD NUMERO_REFERENCIA VARCHAR(100);

-- COMANDO ALTER MODIFY COLUMN 
ALTER TABLE PEDIDOCOMPRA MODIFY COLUMN NUMERO_REFERENCIA VARCHAR(150);

-- COMANDO ALTER CHANGE COLUMN
ALTER TABLE PEDIDOCOMPRA CHANGE COLUMN NUMERO_REFERENCIA REFERENCIA_COMPLETA VARCHAR(150);

-- COMANDO ALTER ADD INDEX
ALTER TABLE PEDIDOCOMPRA ADD INDEX IDX_REFERENCIA (REFERENCIA_COMPLETA);

-- REMOVER ÍNDICE:
DROP INDEX IDX_REFERENCIA ON PEDIDOCOMPRA;

-- REMOVER VISÃO:
DROP VIEW VISTA_PEDIDOS;

-- REMOVER DADOS
TRUNCATE TABLE PEDIDOCOMPRA;

-- ALTERAR NOME DA TABELA
RENAME TABLE PEDIDOCOMPRA TO PEDIDOSCOMPRA;
RENAME TABLE PEDIDOSCOMPRA TO PEDIDOCOMPRA;

-- COMENTÁRIOS NA TABELA
ALTER TABLE PEDIDOCOMPRA COMMENT = 'TABELA DE INFORMAÇÕES DOS PEDIDOS DE COMPRA';

-- ADICIONAR COMENTÁRIO A COLUMNA:
ALTER TABLE PEDIDOCOMPRA MODIFY REFERENCIA_COMPLETA VARCHAR(150) COMMENT 'NÚMERO DE REFERÊNCIA DO PEDIDO DE COMPRA';

-- COMANDO ALTER DROP COLUMN
ALTER TABLE PEDIDOCOMPRA DROP COLUMN REFERENCIA_COMPLETA;

-- CRIAR TABELA PRODUTO_PEDIDO
CREATE TABLE PRODUTO_PEDIDO (
    ID_PEDIDO INT,
    ID_PRODUTO INT,
    QUANTIDADE_SOLICITADA INT NOT NULL,
    PRIMARY KEY (ID_PEDIDO, ID_PRODUTO),
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOCOMPRA(ID_PEDIDO),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);

-- COMANDOS DDL PRODUTO_PEDIDO
-- CRIAR INDEX
CREATE INDEX IDX_ID_PEDIDO 
ON PRODUTO_PEDIDO (ID_PEDIDO);

-- CRIAR VIEW
CREATE VIEW VISTA_PRODUTO_PEDIDO AS
SELECT ID_PEDIDO, ID_PRODUTO, QUANTIDADE_SOLICITADA
FROM PRODUTO_PEDIDO;

-- COMANDO ALTER ADD
ALTER TABLE PRODUTO_PEDIDO ADD OBSERVACAO VARCHAR(255);

-- COMANDO ALTER MODIFY COLUMN 
ALTER TABLE PRODUTO_PEDIDO MODIFY COLUMN OBSERVACAO VARCHAR(300);

-- COMANDO ALTER CHANGE COLUMN
ALTER TABLE PRODUTO_PEDIDO CHANGE COLUMN OBSERVACAO OBSERVACAO_DETALHADA VARCHAR(300);

-- COMANDO ALTER ADD INDEX
ALTER TABLE PRODUTO_PEDIDO ADD INDEX IDX_OBSERVACAO (OBSERVACAO_DETALHADA);

-- REMOVER ÍNDICE:
DROP INDEX IDX_OBSERVACAO ON PRODUTO_PEDIDO;

-- REMOVER VISÃO:
DROP VIEW VISTA_PRODUTO_PEDIDO;

-- REMOVER DADOS
TRUNCATE TABLE PRODUTO_PEDIDO;

-- ALTERAR NOME DA TABELA
RENAME TABLE PRODUTO_PEDIDO TO PRODUTOS_PEDIDOS;
RENAME TABLE PRODUTOS_PEDIDOS TO PRODUTO_PEDIDO;

-- COMENTÁRIOS NA TABELA
ALTER TABLE PRODUTO_PEDIDO COMMENT = 'TABELA ASSOCIATIVA ENTRE PRODUTOS E PEDIDOS DE COMPRA';

-- ADICIONAR COMENTÁRIO A COLUMNA:
ALTER TABLE PRODUTO_PEDIDO MODIFY OBSERVACAO_DETALHADA VARCHAR(300) COMMENT 'OBSERVAÇÃO SOBRE O PRODUTO NO PEDIDO';

-- COMANDO ALTER DROP COLUMN
ALTER TABLE PRODUTO_PEDIDO DROP COLUMN OBSERVACAO_DETALHADA;

-- CRIAR TABELA RECEBIMENTO
CREATE TABLE RECEBIMENTO (
    ID_RECEBIMENTO INT AUTO_INCREMENT PRIMARY KEY,
    DATA_RECEBIMENTO DATE NOT NULL,
    CONDICAO ENUM('ACEITO', 'REJEITADO') NOT NULL,
    MOTIVO_REJEICAO TEXT,
    ID_PEDIDO INT,
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOCOMPRA(ID_PEDIDO)
);

-- COMANDOS DDL RECEBIMENTO
-- CRIAR INDEX
CREATE INDEX IDX_DATA_RECEBIMENTO 
ON RECEBIMENTO (DATA_RECEBIMENTO);

-- CRIAR VIEW
CREATE VIEW VISTA_RECEBIMENTOS AS
SELECT DATA_RECEBIMENTO, CONDICAO
FROM RECEBIMENTO;

-- COMANDO ALTER ADD
ALTER TABLE RECEBIMENTO ADD NUMERO_DOCUMENTO VARCHAR(100);

-- COMANDO ALTER MODIFY COLUMN 
ALTER TABLE RECEBIMENTO MODIFY COLUMN NUMERO_DOCUMENTO VARCHAR(150);

-- COMANDO ALTER CHANGE COLUMN
ALTER TABLE RECEBIMENTO CHANGE COLUMN NUMERO_DOCUMENTO NUMERO_DOCUMENTO_COMPLETO VARCHAR(150);

-- COMANDO ALTER ADD INDEX
ALTER TABLE RECEBIMENTO ADD INDEX IDX_NUMERO_DOCUMENTO (NUMERO_DOCUMENTO_COMPLETO);

-- REMOVER ÍNDICE:
DROP INDEX IDX_NUMERO_DOCUMENTO ON RECEBIMENTO;

-- REMOVER VISÃO:
DROP VIEW VISTA_RECEBIMENTOS;

-- REMOVER DADOS
TRUNCATE TABLE RECEBIMENTO;

-- ALTERAR NOME DA TABELA
RENAME TABLE RECEBIMENTO TO RECEBIMENTOS;
RENAME TABLE RECEBIMENTOS TO RECEBIMENTO;

-- COMENTÁRIOS NA TABELA
ALTER TABLE RECEBIMENTO COMMENT = 'TABELA DE INFORMAÇÕES DOS RECEBIMENTOS DE PRODUTOS';

-- ADICIONAR COMENTÁRIO A COLUMNA:
ALTER TABLE RECEBIMENTO MODIFY NUMERO_DOCUMENTO_COMPLETO VARCHAR(150) COMMENT 'NÚMERO DO DOCUMENTO DO RECEBIMENTO';

-- COMANDO ALTER DROP COLUMN
ALTER TABLE RECEBIMENTO DROP COLUMN NUMERO_DOCUMENTO_COMPLETO;

-- CRIAR TABELA FILIAL
CREATE TABLE FILIAL (
    ID_FILIAL INT AUTO_INCREMENT PRIMARY KEY,
    NOME_FILIAL VARCHAR(255) NOT NULL,
    ENDERECO VARCHAR(255),
    CAPACIDADE_ARMZENAGEM INT
);

-- COMANDOS DDL FILIAL
-- CRIAR INDEX
CREATE INDEX IDX_NOME_FILIAL 
ON FILIAL (NOME_FILIAL);

-- CRIAR VIEW
CREATE VIEW VISTA_FILIAIS AS
SELECT NOME_FILIAL, ENDERECO
FROM FILIAL;

-- COMANDO ALTER ADD
ALTER TABLE FILIAL ADD CODIGO_IDENTIFICACAO VARCHAR(100);

-- COMANDO ALTER MODIFY COLUMN 
ALTER TABLE FILIAL MODIFY COLUMN CODIGO_IDENTIFICACAO VARCHAR(150);

-- COMANDO ALTER CHANGE COLUMN
ALTER TABLE FILIAL CHANGE COLUMN CODIGO_IDENTIFICACAO CODIGO_IDENTIFICACAO_COMPLETO VARCHAR(150);

-- COMANDO ALTER ADD INDEX
ALTER TABLE FILIAL ADD INDEX IDX_CODIGO_IDENTIFICACAO (CODIGO_IDENTIFICACAO_COMPLETO);

-- REMOVER ÍNDICE:
DROP INDEX IDX_CODIGO_IDENTIFICACAO ON FILIAL;

-- REMOVER VISÃO:
DROP VIEW VISTA_FILIAIS;

-- REMOVER DADOS
TRUNCATE TABLE FILIAL;

-- ALTERAR NOME DA TABELA
RENAME TABLE FILIAL TO FILIAIS;
RENAME TABLE FILIAIS TO FILIAL;

-- COMENTÁRIOS NA TABELA
ALTER TABLE FILIAL COMMENT = 'TABELA DE INFORMAÇÕES DAS FILIAIS';

-- ADICIONAR COMENTÁRIO A COLUMNA:
ALTER TABLE FILIAL MODIFY CODIGO_IDENTIFICACAO_COMPLETO VARCHAR(150) COMMENT 'CÓDIGO DE IDENTIFICAÇÃO DA FILIAL';

-- COMANDO ALTER DROP COLUMN
ALTER TABLE FILIAL DROP COLUMN CODIGO_IDENTIFICACAO_COMPLETO;

-- CRIAR TABELA TRANSFERENCIA
CREATE TABLE TRANSFERENCIA (
    ID_TRANSFERENCIA INT AUTO_INCREMENT PRIMARY KEY,
    DATA_TRANSFERENCIA DATE NOT NULL,
    ID_PRODUTO INT,
    QUANTIDADE INT NOT NULL,
    ID_FILIAL_ORIGEM INT,
    ID_FILIAL_DESTINO INT,
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO),
    FOREIGN KEY (ID_FILIAL_ORIGEM) REFERENCES FILIAL(ID_FILIAL),
    FOREIGN KEY (ID_FILIAL_DESTINO) REFERENCES FILIAL(ID_FILIAL)
);

-- COMANDOS DDL TRANSFERENCIA
-- CRIAR INDEX
CREATE INDEX IDX_DATA_TRANSFERENCIA 
ON TRANSFERENCIA (DATA_TRANSFERENCIA);

-- CRIAR VIEW
CREATE VIEW VISTA_TRANSFERENCIAS AS
SELECT DATA_TRANSFERENCIA, ID_PRODUTO, QUANTIDADE
FROM TRANSFERENCIA;

-- COMANDO ALTER ADD
ALTER TABLE TRANSFERENCIA ADD NUMERO_DOCUMENTO VARCHAR(100);

-- COMANDO ALTER MODIFY COLUMN 
ALTER TABLE TRANSFERENCIA MODIFY COLUMN NUMERO_DOCUMENTO VARCHAR(150);

-- COMANDO ALTER CHANGE COLUMN
ALTER TABLE TRANSFERENCIA CHANGE COLUMN NUMERO_DOCUMENTO NUMERO_DOCUMENTO_COMPLETO VARCHAR(150);

-- COMANDO ALTER ADD INDEX
ALTER TABLE TRANSFERENCIA ADD INDEX IDX_NUMERO_DOCUMENTO (NUMERO_DOCUMENTO_COMPLETO);

-- REMOVER ÍNDICE:
DROP INDEX IDX_NUMERO_DOCUMENTO ON TRANSFERENCIA;

-- REMOVER VISÃO:
DROP VIEW VISTA_TRANSFERENCIAS;

-- REMOVER DADOS
TRUNCATE TABLE TRANSFERENCIA;

-- ALTERAR NOME DA TABELA
RENAME TABLE TRANSFERENCIA TO TRANSFERENCIAS;
RENAME TABLE TRANSFERENCIAS TO TRANSFERENCIA;

-- COMENTÁRIOS NA TABELA
ALTER TABLE TRANSFERENCIA COMMENT = 'TABELA DE INFORMAÇÕES DAS TRANSFERÊNCIAS DE PRODUTOS ENTRE FILIAIS';

-- ADICIONAR COMENTÁRIO A COLUMNA:
ALTER TABLE TRANSFERENCIA MODIFY NUMERO_DOCUMENTO_COMPLETO VARCHAR(150) COMMENT 'NÚMERO DO DOCUMENTO DA TRANSFERÊNCIA';

-- COMANDO ALTER DROP COLUMN
ALTER TABLE TRANSFERENCIA DROP COLUMN NUMERO_DOCUMENTO_COMPLETO;

-- REMOVER TABELA:
DROP TABLE IF EXISTS TRANSFERENCIA;
DROP TABLE IF EXISTS FILIAL;
DROP TABLE IF EXISTS RECEBIMENTO;
DROP TABLE IF EXISTS PRODUTO_PEDIDO;
DROP TABLE IF EXISTS PEDIDOCOMPRA;
DROP TABLE IF EXISTS PRODUTO;
DROP TABLE IF EXISTS FORNECEDORES;

-- REMOVER BANCO DE DADOS:
DROP DATABASE CADEIA_DE_SUPRIMENTOS;
