CREATE DATABASE FLYHIGH_AIRLINES;
USE FLYHIGH_AIRLINES;

-- CRIAR TABELA PASSAGEIROS
CREATE TABLE IF NOT EXISTS PASSAGEIROS (
    ID_PASSAGEIROS INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PASSAG VARCHAR(150) NOT NULL,
    CPF_PASSAG VARCHAR(20) NOT NULL UNIQUE,
    TEL_PASSAG VARCHAR(12) NOT NULL,
    ENDERECO_PASSAG VARCHAR(150) NOT NULL
);

-- COMANDOS DDL PASSAGEIROS
-- CRIAR INDEX
CREATE INDEX IDX_CPF_PASSAG ON PASSAGEIROS (CPF_PASSAG);

-- CRIAR VIEW
CREATE VIEW VISTA_PASSAGEIROS AS
SELECT NOME_PASSAG, CPF_PASSAG, TEL_PASSAG
FROM PASSAGEIROS;

-- COMANDO ALTER ADD
ALTER TABLE PASSAGEIROS ADD EMAIL_PASSAG VARCHAR(100);

-- COMANDO ALTER MODIFY COLUMN 
ALTER TABLE PASSAGEIROS MODIFY COLUMN EMAIL_PASSAG VARCHAR(150);

-- COMANDO ALTER CHANGE COLUMN
ALTER TABLE PASSAGEIROS CHANGE COLUMN EMAIL_PASSAG EMAIL_COMPLETO VARCHAR(150);

-- COMANDO ALTER ADD INDEX
ALTER TABLE PASSAGEIROS ADD INDEX IDX_EMAIL (EMAIL_COMPLETO);

-- REMOVER ÍNDICE:
DROP INDEX IDX_EMAIL ON PASSAGEIROS;

-- REMOVER VISÃO:
DROP VIEW VISTA_PASSAGEIROS;

-- REMOVER DADOS
TRUNCATE TABLE PASSAGEIROS;

-- ALTERAR NOME DA TABELA
RENAME TABLE PASSAGEIROS TO PASSAGEIROSANTIGOS;
RENAME TABLE PASSAGEIROSANTIGOS TO PASSAGEIROS;

-- COMENTÁRIOS NA TABELA
ALTER TABLE PASSAGEIROS COMMENT = 'TABELA DE INFORMAÇÕES DOS PASSAGEIROS';

-- ADICIONAR COMENTÁRIO A COLUNA:
ALTER TABLE PASSAGEIROS MODIFY EMAIL_COMPLETO VARCHAR(150) COMMENT 'EMAIL DO PASSAGEIRO';

-- COMANDO ALTER DROP COLUMN
ALTER TABLE PASSAGEIROS DROP COLUMN EMAIL_COMPLETO;

-- CRIAR TABELA VOOS
CREATE TABLE IF NOT EXISTS VOOS (
    ID_VOO INT PRIMARY KEY AUTO_INCREMENT,
    ORIGEM VARCHAR(150) NOT NULL,
    DESTINO VARCHAR(150) NOT NULL,
    HORARIO_CHEGADA DATETIME,
    HORARIO_SAIDA DATETIME
);

-- COMANDOS DDL VOOS
-- CRIAR INDEX
CREATE INDEX IDX_ORIGEM_DESTINO ON VOOS (ORIGEM, DESTINO);

-- CRIAR VIEW
CREATE VIEW VISTA_VOOS AS
SELECT ORIGEM, DESTINO, HORARIO_CHEGADA, HORARIO_SAIDA
FROM VOOS;

-- COMANDO ALTER ADD
ALTER TABLE VOOS ADD COMPANHIA_AEREA VARCHAR(100);

-- COMANDO ALTER MODIFY COLUMN 
ALTER TABLE VOOS MODIFY COLUMN COMPANHIA_AEREA VARCHAR(150);

-- COMANDO ALTER CHANGE COLUMN
ALTER TABLE VOOS CHANGE COLUMN COMPANHIA_AEREA COMPANHIA_AEREA_COMPLETA VARCHAR(150);

-- COMANDO ALTER ADD INDEX
ALTER TABLE VOOS ADD INDEX IDX_COMPANHIA_AEREA (COMPANHIA_AEREA_COMPLETA);

-- REMOVER ÍNDICE:
DROP INDEX IDX_COMPANHIA_AEREA ON VOOS;

-- REMOVER VISÃO:
DROP VIEW VISTA_VOOS;

-- REMOVER DADOS
TRUNCATE TABLE VOOS;

-- ALTERAR NOME DA TABELA
RENAME TABLE VOOS TO VOOSANTIGOS;
RENAME TABLE VOOSANTIGOS TO VOOS;

-- COMENTÁRIOS NA TABELA
ALTER TABLE VOOS COMMENT = 'TABELA DE INFORMAÇÕES DOS VOOS';

-- ADICIONAR COMENTÁRIO A COLUNA:
ALTER TABLE VOOS MODIFY COMPANHIA_AEREA_COMPLETA VARCHAR(150) COMMENT 'NOME DA COMPANHIA AÉREA QUE OPERA O VOO';

-- COMANDO ALTER DROP COLUMN
ALTER TABLE VOOS DROP COLUMN COMPANHIA_AEREA_COMPLETA;

-- CRIAR TABELA AEROPORTOS
CREATE TABLE IF NOT EXISTS AEROPORTOS (
    ID_AEROPORTO INT PRIMARY KEY AUTO_INCREMENT,
    PONTO_PARTIDA VARCHAR(150) NOT NULL,
    PONTO_CHEGADA VARCHAR(150) NOT NULL
);

-- COMANDOS DDL AEROPORTOS
-- CRIAR INDEX
CREATE INDEX IDX_PONTO_PARTIDA_CHEGADA ON AEROPORTOS (PONTO_PARTIDA, PONTO_CHEGADA);

-- CRIAR VIEW
CREATE VIEW VISTA_AEROPORTOS AS
SELECT PONTO_PARTIDA, PONTO_CHEGADA
FROM AEROPORTOS;

-- COMANDO ALTER ADD
ALTER TABLE AEROPORTOS ADD CODIGO_AEROPORTO VARCHAR(10);

-- COMANDO ALTER MODIFY COLUMN 
ALTER TABLE AEROPORTOS MODIFY COLUMN CODIGO_AEROPORTO VARCHAR(15);

-- COMANDO ALTER CHANGE COLUMN
ALTER TABLE AEROPORTOS CHANGE COLUMN CODIGO_AEROPORTO CODIGO_AEROPORTO_COMPLETO VARCHAR(15);

-- COMANDO ALTER ADD INDEX
ALTER TABLE AEROPORTOS ADD INDEX IDX_CODIGO_AEROPORTO (CODIGO_AEROPORTO_COMPLETO);

-- REMOVER ÍNDICE:
DROP INDEX IDX_CODIGO_AEROPORTO ON AEROPORTOS;

-- REMOVER VISÃO:
DROP VIEW VISTA_AEROPORTOS;

-- REMOVER DADOS
TRUNCATE TABLE AEROPORTOS;

-- ALTERAR NOME DA TABELA
RENAME TABLE AEROPORTOS TO AEROPORTOSANTIGOS;
RENAME TABLE AEROPORTOSANTIGOS TO AEROPORTOS;

-- COMENTÁRIOS NA TABELA
ALTER TABLE AEROPORTOS COMMENT = 'TABELA DE INFORMAÇÕES DOS AEROPORTOS';

-- ADICIONAR COMENTÁRIO A COLUNA:
ALTER TABLE AEROPORTOS MODIFY CODIGO_AEROPORTO_COMPLETO VARCHAR(15) COMMENT 'CÓDIGO DO AEROPORTO';

-- COMANDO ALTER DROP COLUMN
ALTER TABLE AEROPORTOS DROP COLUMN CODIGO_AEROPORTO_COMPLETO;

-- CRIAR TABELA AERONAVES
CREATE TABLE IF NOT EXISTS AERONAVES (
    ID_AERONAVE INT PRIMARY KEY AUTO_INCREMENT
);

-- COMANDOS DDL AERONAVES
-- CRIAR INDEX
CREATE INDEX IDX_ID_AERONAVE ON AERONAVES (ID_AERONAVE);

-- CRIAR VIEW
CREATE VIEW VISTA_AERONAVES AS
SELECT ID_AERONAVE
FROM AERONAVES;

-- COMANDO ALTER ADD
ALTER TABLE AERONAVES ADD MODELO VARCHAR(50);

-- COMANDO ALTER MODIFY COLUMN 
ALTER TABLE AERONAVES MODIFY COLUMN MODELO VARCHAR(75);

-- COMANDO ALTER CHANGE COLUMN
ALTER TABLE AERONAVES CHANGE COLUMN MODELO MODELO_COMPLETO VARCHAR(75);

-- COMANDO ALTER ADD INDEX
ALTER TABLE AERONAVES ADD INDEX IDX_MODELO (MODELO_COMPLETO);

-- REMOVER ÍNDICE:
DROP INDEX IDX_MODELO ON AERONAVES;

-- REMOVER VISÃO:
DROP VIEW VISTA_AERONAVES;

-- REMOVER DADOS
TRUNCATE TABLE AERONAVES;

-- ALTERAR NOME DA TABELA
RENAME TABLE AERONAVES TO AERONAVESANTIGOS;
RENAME TABLE AERONAVESANTIGOS TO AERONAVES;

-- COMENTÁRIOS NA TABELA
ALTER TABLE AERONAVES COMMENT = 'TABELA DE INFORMAÇÕES DAS AERONAVES';

-- ADICIONAR COMENTÁRIO A COLUNA:
ALTER TABLE AERONAVES MODIFY MODELO_COMPLETO VARCHAR(75) COMMENT 'MODELO DA AERONAVE';

-- COMANDO ALTER DROP COLUMN
ALTER TABLE AERONAVES DROP COLUMN MODELO_COMPLETO;

-- CRIAR TABELA FUNCIONARIOS
CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
    ID_FUNCIONARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PILOTO VARCHAR(30) NOT NULL,
    COMISSARIOS_ABORDO VARCHAR(150) NOT NULL,
    EQUIPE_SOLO VARCHAR(150) NOT NULL
);

-- COMANDOS DDL FUNCIONARIOS
-- CRIAR INDEX
CREATE INDEX IDX_NOME_PILOTO ON FUNCIONARIOS (NOME_PILOTO);

-- CRIAR VIEW
CREATE VIEW VISTA_FUNCIONARIOS AS
SELECT NOME_PILOTO, COMISSARIOS_ABORDO, EQUIPE_SOLO
FROM FUNCIONARIOS;

-- COMANDO ALTER ADD
ALTER TABLE FUNCIONARIOS ADD TIPO_FUNCIONARIO VARCHAR(20);

-- COMANDO ALTER MODIFY COLUMN 
ALTER TABLE FUNCIONARIOS MODIFY COLUMN TIPO_FUNCIONARIO VARCHAR(30);

-- COMANDO ALTER CHANGE COLUMN
ALTER TABLE FUNCIONARIOS CHANGE COLUMN TIPO_FUNCIONARIO TIPO_FUNCIONARIO_COMPLETO VARCHAR(30);

-- COMANDO ALTER ADD INDEX
ALTER TABLE FUNCIONARIOS ADD INDEX IDX_TIPO_FUNCIONARIO (TIPO_FUNCIONARIO_COMPLETO);

-- REMOVER ÍNDICE:
DROP INDEX IDX_TIPO_FUNCIONARIO ON FUNCIONARIOS;

-- REMOVER VISÃO:
DROP VIEW VISTA_FUNCIONARIOS;

-- REMOVER DADOS
TRUNCATE TABLE FUNCIONARIOS;

-- ALTERAR NOME DA TABELA
RENAME TABLE FUNCIONARIOS TO FUNCIONARIOSANTIGOS;
RENAME TABLE FUNCIONARIOSANTIGOS TO FUNCIONARIOS;

-- COMENTÁRIOS NA TABELA
ALTER TABLE FUNCIONARIOS COMMENT = 'TABELA DE INFORMAÇÕES DOS FUNCIONÁRIOS';

-- ADICIONAR COMENTÁRIO A COLUNA:
ALTER TABLE FUNCIONARIOS MODIFY TIPO_FUNCIONARIO_COMPLETO VARCHAR(30) COMMENT 'TIPO DE FUNCIONÁRIO (PILOTO, COMISSÁRIO, ETC.)';

-- COMANDO ALTER DROP COLUMN
ALTER TABLE FUNCIONARIOS DROP COLUMN TIPO_FUNCIONARIO_COMPLETO;

-- CRIAR TABELA RESERVAS
CREATE TABLE IF NOT EXISTS RESERVAS (
    ID_RESERVA INT PRIMARY KEY AUTO_INCREMENT,
    ID_PASSAGEIROS INT NOT NULL,
    ID_VOO INT NOT NULL
);

-- COMANDOS DDL RESERVAS
-- CRIAR INDEX
CREATE INDEX IDX_ID_PASSAGEIROS_VOO ON RESERVAS (ID_PASSAGEIROS, ID_VOO);

-- CRIAR VIEW
CREATE VIEW VISTA_RESERVAS AS
SELECT ID_RESERVA, ID_PASSAGEIROS, ID_VOO
FROM RESERVAS;

-- COMANDO ALTER ADD
ALTER TABLE RESERVAS ADD STATUS_RESERVA VARCHAR(20);

-- COMANDO ALTER MODIFY COLUMN 
ALTER TABLE RESERVAS MODIFY COLUMN STATUS_RESERVA VARCHAR(30);

-- COMANDO ALTER CHANGE COLUMN
ALTER TABLE RESERVAS CHANGE COLUMN STATUS_RESERVA STATUS_RESERVA_COMPLETO VARCHAR(30);

-- COMANDO ALTER ADD INDEX
ALTER TABLE RESERVAS ADD INDEX IDX_STATUS_RESERVA (STATUS_RESERVA_COMPLETO);

-- REMOVER ÍNDICE:
DROP INDEX IDX_STATUS_RESERVA ON RESERVAS;

-- REMOVER VISÃO:
DROP VIEW VISTA_RESERVAS;

-- REMOVER DADOS
TRUNCATE TABLE RESERVAS;

-- ALTERAR NOME DA TABELA
RENAME TABLE RESERVAS TO RESERVASANTIGAS;
RENAME TABLE RESERVASANTIGAS TO RESERVAS;

-- COMENTÁRIOS NA TABELA
ALTER TABLE RESERVAS COMMENT = 'TABELA DE INFORMAÇÕES DAS RESERVAS';

-- ADICIONAR COMENTÁRIO A COLUNA:
ALTER TABLE RESERVAS MODIFY STATUS_RESERVA_COMPLETO VARCHAR(30) COMMENT 'STATUS DA RESERVA (CONFIRMADA, CANCELADA, ETC.)';

-- COMANDO ALTER DROP COLUMN
ALTER TABLE RESERVAS DROP COLUMN STATUS_RESERVA_COMPLETO;

DROP TABLE IF EXISTS RESERVAS;
DROP TABLE IF EXISTS FUNCIONARIOS;
DROP TABLE IF EXISTS AERONAVES;
DROP TABLE IF EXISTS AEROPORTOS;
DROP TABLE IF EXISTS VOOS;
DROP TABLE IF EXISTS PASSAGEIROS;

DROP DATABASE IF EXISTS FLYHIGH_AIRLINES;
